name: CI
on:
  push:
    branches:
      - develop

jobs:
  build_appbundle:
    name: Flutter Build (Android)
    env:
      APPCENTER_BUILD_ID: 1
    #needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter build appbundle --release --flavor googlePlay
      - run: mkdir -p android/app/build/outputs/bundle/
      - run: mv build/app/outputs/bundle/appcenterRelease/app-appcenter-release.aab $_
      # Upload generated appbundle to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: android/app/build/outputs/bundle/app-appcenter-release.aab