name: QA
on:
  pull_request:
    branches:
      - distribute

jobs:
  check_commit_message:
    name: Check Commit Message for Release Tag
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.getcommittag.outputs.release }}
    steps:
      - name: get commit message
        run: |
          echo $(git log --format=%B -n 1 ${{ github.event.after }})
      # "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
      - run: echo $commitmsg
      - name: show commit message
        id: getcommittag
        run: echo "::set-output name=release::$(contains($commitmsg, 'RELEASE'))"

  emulator_test:
    name: Remaining Test Job
    needs: check_commit_message
    if: ${{needs.check_commit_message.outputs.output}} == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Run Remaining Test Job
        run: echo "Running Remaining Test Job"
      - run: echo ${{needs.check_commit_message.outputs.output}}

  alpha_release:
    name: Remaining Release Job
    needs: check_commit_message
    if: ${{needs.check_commit_message.outputs.output}} == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Run Remaining Release Job
        run: echo "Running Remaining Release Job"
      - run: echo ${{needs.check_commit_message.outputs.output}}