name: QA
on:
  pull_request:
    branches:
      - distribute

jobs:

  emulator_test:
    name: Remaining Test Job
    if: startsWith(github.event.pull_request.body, '[RELEASE]') != true
    runs-on: ubuntu-latest
    steps:
      - name: Run Remaining Test Job
        run: echo "Running Remaining Test Job"
      - run: echo ${{needs.check_commit_message.outputs.output}}

  alpha_release:
    name: Remaining Release Job
    if: startsWith(github.event.pull_request.body, '[RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - name: Run Remaining Release Job
        run: echo "Running Remaining Release Job"
      - run: echo ${{needs.check_commit_message.outputs.output}}