name: QA - Internal
on:
  pull_request:
    branches:
      - distribute

jobs:
  check_is_not_release:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Validate no [RELEASE] tag on commit message
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((?![RELEASE]).)*$'
          flags: 'gm'
          error: 'This is a [RELEASE] tagged commit. Skipping remaining jobs..'

  flutter_drive_test:
    name: Run Flutter Drive Test
    needs: check_is_not_release
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run onboarding drive test
        env:
          ANDROID_BUILD_ID: 1
        uses: reactivecircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            export ANDROID_DEBUG=true
            flutter pub get
            flutter drive --driver=test_driver/integration_driver.dart --target=integration_test/app_test.dart