name: QA - Internal
on:
  pull_request:
    branches:
      - distribute

jobs:
  check_is_not_release:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Validate no [RELEASE] tag on commit message
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((?!RELEASE).)*$'
          flags: 'gm'
          error: 'This is a [RELEASE] tagged commit. Skipping remaining jobs..'

  job2:
    name: Remaining Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Id
        run: echo "Running Remaining Test Job"

